name: meta-review
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - pip