name: meta-review
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - pip
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.13.1
  - matplotlib=3.9.2
  - pyarrow=17.0.0
  - ncurses=6.4
  - sqlite=3.45.3
  - tk=8.6.14
  - xz=5.4.6
  - zlib=1.2.13
  - ld_impl_linux-64=2.40
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - openssl=3.4.0
  - pip:
    - accelerate==1.1.1
    - aiofiles==23.2.1
    - aiohttp==3.10.10
    - attrs==24.2.0
    - bitsandbytes==0.44.1
    - datasets==2.14.7
    - deepspeed==0.16.0
    - dill==0.3.7
    - fastapi==0.115.2
    - flash-attn==2.7.0.post2
    - huggingface-hub==0.26.3
    - matplotlib==3.9.2
    - pyarrow==17.0.0
    - pydantic==2.9.2
    - safetensors==0.4.5
    - sentencepiece==0.2.0
    - tqdm==4.66.5
    - transformers==4.46.3
    - uvicorn==0.32.0
    - wandb==0.19.0
    - websockets==12.0